name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci  # 'npm ci' is faster and more reliable for CI environments

    # Step 4: Start the server
    - name: Start server
      run: npm start &
      env:
        NODE_ENV: test  # Optionally set NODE_ENV to test if required

    # Step 5: Wait for the server to be ready
    - name: Wait for server to be ready
      uses: jakejarvis/wait-on-action@v2
      with:
        url: 'http://localhost:3000'  # Adjust to match your app's start URL

    # Step 6: Run Cypress tests
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        record: true  # Record the test run on Cypress Dashboard (optional)
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}  # Ensure you set this secret in GitHub

    # Optionally: Upload Cypress artifacts (screenshots and videos) if tests fail
    - name: Upload Cypress Artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: cypress-artifacts
        path: cypress/screenshots/**/*.png,cypress/videos/**/*.mp4
