name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Start server
      run: npm start &
      env:
        NODE_ENV: test

    - name: Wait for server to be ready
      uses: jakejarvis/wait-on-action@v2
      with:
        url: 'http://localhost:3000'

    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    - name: Upload Cypress Artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: cypress-artifacts
        path: cypress/screenshots/**/*.png,cypress/videos/**/*.mp4
